# This is a basic workflow to help you get started with Actions

name: Publish

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install Pester
        shell: pwsh
        run: Install-Module Pester -RequiredVersion 5.1.1 -Force -Scope CurrentUser

      - name: Run Test
        env:
          PSGalleryAPIKey: ${{ secrets.PSGalleryAPIKey }}
        shell: pwsh
        run: SimpleRequest/Tests/SimpleRequest.Tests.ps1

      - name: Install PowerShellGet
        shell: pwsh
        run: Install-Module -Name PowerShellGet -Force

      - name: Publish
        env:
          PSGalleryAPIKey: ${{ secrets.PSGalleryAPIKey }}
        shell: pwsh
        run: tool/publish.ps1
